name = "kizamu-api-server"
main = "./src/index.ts"
compatibility_date = "2025-02-24"
compatibility_flags = ["nodejs_compat"]

[env.local.vars]
NODE_ENV = "development"
AUTH0_CLIENT_ID = "lexi-nova-api-auth0"
AUTH0_AUTH_ORIGIN = "https://lexinova-dev.jp.auth0.com"
AUTH0_ISSUER = "https://lexinova-dev.jp.auth0.com/"

[[env.local.hyperdrive]]
binding = "HYPERDRIVE"
id = "7a174f524de149e790e38d17f124047c"

[env.staging.vars]
NODE_ENV = "staging"
AUTH0_CLIENT_ID = "lexi-nova-api-auth0"
AUTH0_AUTH_ORIGIN = "https://lexinova-dev.jp.auth0.com"
AUTH0_ISSUER = "https://lexinova-dev.jp.auth0.com/"

[[env.staging.hyperdrive]]
binding = "HYPERDRIVE"
id = "7a174f524de149e790e38d17f124047c"