name                = "kizamu-web-app"
main                = "./workers/app.ts"
compatibility_date  = "2025-04-04"
compatibility_flags = ["nodejs_compat"]
observability       = { enabled = true }

[vars]
NODE_ENV           = "production"
AUTH0_CLIENT_ID    = "hGky8hwPqc0Id97cUj0tF4rfdQSGk0lQ"
AUTH0_REDIRECT_URI = "https://kizamu-web-app.7d-yama.workers.dev/callback"
AUTH0_AUTH_ORIGIN  = "https://lexinova-dev.jp.auth0.com"
AUTH0_ISSUER       = "https://lexinova-dev.jp.auth0.com/"
AUTH0_AUDIENCE     = "lexi-nova-api-auth0"

[[kv_namespaces]]
binding = "kizamu_session"
id      = "a53a1293ead84b5b81a4f060f99f403a"

[[services]]
binding = "SERVER"
service = "kizamu-api-server-staging"
